function gwt_validation_sample(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',wc='.cache.html',_='/',Xb='0F2E7F2703165A4EE6E04DDC56476AF0',Yb='17ACC7C077513F264DD9477481F5FC3C',Zb='1CF397BD3CCC63F61020A6F9B323423C',$b='2085047FED965019C48F03F6470884A5',_b='2F2F329F850A76DDADBC9C28251D4B88',ac='2FC973FF8D603E4A07BFFDD3CB32F40A',cc='39415BAE7900D9E665D8AC7342CC9597',dc='5B04224F5415CA5472F5E34B1708C381',fc='7CAC77C90EDAE0E438540AF7DB53CFA9',gc='84FFDDA21A43985537C2D33EE7173109',hc='8B6F54F53B9568B0E2622F9AE9DFABAC',ic='9AFA6DBEA69039EAA83C60902FDD203E',jc='9EF955E96B190647F13756572069F5FD',vc=':',ob='::',Ec='<script defer="defer">gwt_validation_sample.onInjectionDone(\'gwt_validation_sample\')<\/script>',hb='<script id="',rb='=',$='?',kc='A1193FB8BD9B036765053A570AF83C04',lc='B23C562D2FD67ED3F260AA12B42C1B65',mc='BB5A71CF321535A1304FC0AA5B97E632',tb='Bad handler "',nc='C1D27A53C9F4E289BE39F956AAB59A3D',oc='C727B274175008E30B191E97AB48F5F5',pc='D1A3CCB3F0BF0FC5B554E332AB7081DD',qc='D1C514EF6FB450596B0D30106AA79E9F',rc='D6D309CBE0844DF186B3448156B947D1',Dc='DOMContentLoaded',sc='E0CDDC2A44FA222A3983BC0C017CBDC3',tc='F9C0616596A5175916D47FAEBE7B7478',uc='FFD852B8DA2A4114E99112A7867FFE70',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_gwt_validation_sample',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',Wb='default',Cb='en',Y='end',bc='es',ec='fr',Qb='gecko',Rb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',xc='gwt/clean/clean.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Q='gwt_validation_sample',eb='gwt_validation_sample.nocache.js',nb='gwt_validation_sample::',Cc='head',Ub='hosted.html?gwt_validation_sample',Bc='href',Pb='ie6',Ob='ie8',Nb='ie9',xb='iframe',ab='img',yb="javascript:''",yc='link',Tb='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Mb='msie',mb='name',Jb='opera',zb='position:absolute;width:0;height:0;border:none',zc='rel',Lb='safari',db='script',Vb='selectingPermutation',R='startup',Ac='stylesheet',fb='undefined',Sb='unknown',Ib='user.agent',Kb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}gwt_validation_sample=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={'default':0,en:1,es:2,fr:3};v[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Jb)!=-1}())return Jb;if(function(){return b.indexOf(Kb)!=-1}())return Lb;if(function(){return b.indexOf(Mb)!=-1&&m.documentMode>=9}())return Nb;if(function(){return b.indexOf(Mb)!=-1&&m.documentMode>=8}())return Ob;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Pb;if(function(){return b.indexOf(Qb)!=-1}())return Rb;return Sb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};gwt_validation_sample.onScriptLoad=function(){if(I){q=true;B()}};gwt_validation_sample.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Ub;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Vb});if(!A()){try{G([Wb,Nb],Xb);G([Wb,Lb],Yb);G([Wb,Rb],Zb);G([Wb,Jb],$b);G([Cb,Jb],_b);G([Cb,Rb],ac);G([bc,Jb],cc);G([Cb,Lb],dc);G([ec,Rb],fc);G([Cb,Nb],gc);G([ec,Ob],hc);G([bc,Nb],ic);G([bc,Rb],jc);G([Wb,Ob],kc);G([ec,Pb],lc);G([Wb,Pb],mc);G([ec,Lb],nc);G([Cb,Pb],oc);G([bc,Lb],pc);G([ec,Nb],qc);G([bc,Pb],rc);G([Cb,Ob],sc);G([ec,Jb],tc);G([bc,Ob],uc);K=w[H(Bb)][H(Ib)];var M=K.indexOf(vc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+wc}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[xc]){var a=m.createElement(yc);__gwt_stylesLoaded[xc]=a;a.setAttribute(zc,Ac);a.setAttribute(Bc,s+xc);m.getElementsByTagName(Cc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Dc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Dc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:T});m.write(Ec)}
gwt_validation_sample();