function gwt_validation_sample(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Eb='&',wc='.cache.html',_='/',Xb='011DBE6287E90F65AC50BE86ACE9F59B',Yb='25071B643073989F462206D19EA090F4',Zb='2D0D04A0A349D065354DB1C1491585B3',_b='2E7D515D98C16FDF14522842C254986D',bc='306B0248BD39734CDAADB9EA1B77D08B',cc='3F9BE2FC2FB62F4F1CAD0D955D8EFD1F',dc='44BF0C32DD54528E2C26D8950225A471',ec='4D7C95C2743B07B592DB60A08B2F36AE',fc='4FC62856AAF84E261F93E9F42BBA00B4',gc='523951C5EC35BF7F8C6BADB3DA5B742A',hc='54E0F5A983405C51238B22401DAC7432',ic='5B9EFAB878E7F94B7B5A55730EE021B0',jc='6316DA6563E21A643E8FDA1EEFD7455B',kc='640DFDD7B1A8B2E7D83BA85C601F7147',lc='6C57C64DB1C1585F8DAA73CD7DBBB642',mc='6F2FF806C63EF0DB50C9797FE3756709',nc='7E7E973BD037585C9FA477BE785F2392',oc='96824B2D85D8F8DA9952DEE9DD59ADB9',vc=':',ob='::',Ec='<script defer="defer">gwt_validation_sample.onInjectionDone(\'gwt_validation_sample\')<\/script>',hb='<script id="',rb='=',$='?',tb='Bad handler "',pc='CD4F225E40DE0774A3E5C2C18940C3CA',qc='D10913605FA1F450FB51DA56A5F7306F',rc='D44C8284A0CC2BBB16CDCE016ECC1E47',sc='D554D33836B144081105D4FF659ADF7F',tc='D80BD4D4242C4108B36C38D6D0D84839',Dc='DOMContentLoaded',uc='E7A8345C033A0D85BBF2F953136C8EDB',jb='SCRIPT',Hb='Unexpected exception in locale detection, using default: ',Gb='_',Fb='__gwt_Locale',gb='__gwt_marker_gwt_validation_sample',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',ac='default',Cb='en',Y='end',Wb='es',$b='fr',Qb='gecko',Rb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',xc='gwt/clean/clean.css',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',Q='gwt_validation_sample',eb='gwt_validation_sample.nocache.js',nb='gwt_validation_sample::',Cc='head',Ub='hosted.html?gwt_validation_sample',Bc='href',Pb='ie6',Ob='ie8',Nb='ie9',xb='iframe',ab='img',yb="javascript:''",yc='link',Tb='loadExternalRefs',Bb='locale',Db='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Mb='msie',mb='name',Jb='opera',zb='position:absolute;width:0;height:0;border:none',zc='rel',Lb='safari',db='script',Vb='selectingPermutation',R='startup',Ac='stylesheet',fb='undefined',Sb='unknown',Ib='user.agent',Kb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}gwt_validation_sample=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var b=null;var c=Cb;try{if(!b){var d=location.search;var e=d.indexOf(Db);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Eb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Bb)}if(!b){b=l[Fb]}if(b){c=b}while(b&&!E(Bb,b)){var h=b.lastIndexOf(Gb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Hb+a)}l[Fb]=c;return b||Cb};u[Bb]={'default':0,en:1,es:2,fr:3};v[Ib]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Jb)!=-1}())return Jb;if(function(){return b.indexOf(Kb)!=-1}())return Lb;if(function(){return b.indexOf(Mb)!=-1&&m.documentMode>=9}())return Nb;if(function(){return b.indexOf(Mb)!=-1&&m.documentMode>=8}())return Ob;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Pb;if(function(){return b.indexOf(Qb)!=-1}())return Rb;return Sb};u[Ib]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};gwt_validation_sample.onScriptLoad=function(){if(I){q=true;B()}};gwt_validation_sample.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=Ub;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Vb});if(!A()){try{G([Wb,Rb],Xb);G([Wb,Nb],Yb);G([Wb,Lb],Zb);G([$b,Jb],_b);G([ac,Lb],bc);G([Cb,Rb],cc);G([Cb,Nb],dc);G([Wb,Pb],ec);G([Cb,Pb],fc);G([$b,Pb],gc);G([ac,Pb],hc);G([$b,Nb],ic);G([$b,Rb],jc);G([Wb,Ob],kc);G([ac,Rb],lc);G([$b,Ob],mc);G([ac,Ob],nc);G([Cb,Ob],oc);G([Cb,Lb],pc);G([$b,Lb],qc);G([ac,Jb],rc);G([ac,Nb],sc);G([Wb,Jb],tc);G([Cb,Jb],uc);K=w[H(Bb)][H(Ib)];var M=K.indexOf(vc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+wc}catch(a){return}}var N;function O(){if(!r){r=true;if(!__gwt_stylesLoaded[xc]){var a=m.createElement(yc);__gwt_stylesLoaded[xc]=a;a.setAttribute(zc,Ac);a.setAttribute(Bc,s+xc);m.getElementsByTagName(Cc)[0].appendChild(a)}B();if(m.removeEventListener){m.removeEventListener(Dc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(Dc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:Tb,millis:(new Date).getTime(),type:T});m.write(Ec)}
gwt_validation_sample();