package com.google.gwt.validation.client;

import com.google.gwt.validation.client.interfaces.IInvalidConstraint;

/**
 * This class is for denoting instances where a particular object 
 * has failed the validation.  These are generated by the validator
 * as part of the validation process.
 * 
 * @author chris
 *
 */
public class InvalidConstraint<T> implements IInvalidConstraint<T> {

	private String itemName;
	private String message;
	
	//objects
	private T rootObject;
	private Object value;
	
	//property path
	private String propertyPath;
	
	public InvalidConstraint(String itemName, String message) {
		
		this.itemName = itemName;
		this.message = message;
		
		this.propertyPath = this.itemName;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public void setInvalidObject(T rootObject) {
		this.rootObject = rootObject;
	}

	public void setValue(Object value) {
		this.value = value;
	}

	public void setPropertyPath(String propertyPath) {
		this.propertyPath = propertyPath;
	}

	@Override
	public String toString() {
		return this.propertyPath + " : " + this.message;
	}

	public T getInvalidObject() {
		return this.rootObject;
	}

	public String getPropertyPath() {
		if(this.propertyPath == null || this.propertyPath.trim().length() == 0) return this.itemName;
		
		return this.propertyPath;
	}

	public Object getValue() {
		return this.value;
	}
	
}
